# 1.复制安装部署包到目标机器
- name: "step_1a copy the ansible local install archive package {{packages_home}}/{{package_filename}} to remote {{ansible_hostname}}@{{temp_path}}"
  copy:
    src:  "{{packages_home}}/{{package_filename}}"
    dest: "{{temp_path}}/"

# 2.准备安装环境
- name: "step_2a create the install path {{install_path}}"
  file:
    state: "directory"
    path: "{{install_path}}"
- name: "step_2b create the data path {{data_path}}"
  file:
    state: "directory"
    path: "{{data_path}}"
- name: "step_2c create the log path {{log_path}}"
  file:
    state: "directory"
    path: "{{log_path}}"

# 3.解压安装文件
- name: "step_3a unarchive the install package {{temp_path}}/{{package_filename}} to {{ install_path }}"
  unarchive:
    copy: no
    src: "{{temp_path}}/{{package_filename}}"
    dest: "{{ install_path }}"

# 4.准备配置文件
- name: "step_4a prepare the {{role}} config of {{install_path}}/{{unarchive_folder_name}}/conf/zoo.cfg"
  template:
    backup: yes
    src: zoo.cfg.j2
    dest: "{{install_path}}/{{unarchive_folder_name}}/conf/zoo.cfg"
- name: "step_4b prepare the {{role}} config of {{data_path}}/myid"
  template:
    backup: yes
    src: myid.j2
    dest: "{{data_path}}/myid"
- name: "step_4c config the java run env for {{role}}"
  template:
    backup: yes
    src: java.env.j2
    dest: "{{install_path}}/{{unarchive_folder_name}}/conf/java.env"
- name: "step_4d config the log4j config of {{install_path}}/{{unarchive_folder_name}}/conf/log4j.properties"
  template:
    backup: yes
    src: log4j.properties.j2
    dest: "{{install_path}}/{{unarchive_folder_name}}/conf/log4j.properties"

# 5.准备端口
- name: "step_5a permit the port {{ZOOKEEPER_PORT}},2888,3888,{{ZOOKEEPER_ADMIN_SERVER_PORT}}"
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
  with_items:
    - "{{ZOOKEEPER_PORT}}/tcp"
    - "2888/tcp"
    - "3888/tcp"
    - "{{ZOOKEEPER_ADMIN_SERVER_PORT}}/tcp"
  #notify: firewalld reload
- name: "step_5b firewalld reload"
  command: firewall-cmd --reload
  ignore_errors: yes

# 6.启动服务
- name: "step_6a register the service zookeeper to systemd"
  template:
    backup: yes
    mode: 0644
    src: "zookeeper.service.j2"
    dest: "{{REMOTE_SYSTEMD_SERVICE_DIR}}/zookeeper.service"
- name: "step_6b restart service"
  systemd:
    name: "zookeeper"
    enabled: yes
    daemon_reload: yes
    state: restarted

# 7.检查
# - name: "step_7a check the zookeeper 2181 port is ok"
#   wait_for:
#     host: localhost
#     port: {{ZOOKEEPER_PORT}}
#     delay: 10
#     timeout: 60
