- name: 打开防火墙
  shell: firewall-cmd --zone=public --add-port={{ MONGOS_PORT }}/tcp --permanent && \
         firewall-cmd --reload
  ignore_errors: yes
- name: 拷贝配置文件
  template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf

- name: copy systemd conf
  template:
    src: mongos.service
    dest: /usr/lib/systemd/system/mongos.service
- name: chmod
  file:
    path: /usr/lib/systemd/system/mongos.service
    mode: 0755

- name: 开机启用 mongos 服务
  shell: systemctl enable mongos
  ignore_errors: true

- name: start mongos
  shell: systemctl daemon-reload && systemctl restart mongos
  ignore_errors: yes

- name: 轮询等待 mongos 服务运行
  shell: "systemctl is-active mongos.service"
  register: mongos_status
  until: '"active" in mongos_status.stdout'
  retries: 3
  delay: 10
  ignore_errors: true

- name: start mongos
  shell: systemctl daemon-reload && systemctl restart mongos
  ignore_errors: yes
  when: '"active" not in mongos_status.stdout'

- block:
  - name: 拷贝 add-user.js
    template:
      src: add-user.js.j2
      dest: /opt/cbimeasz/mongo-cluster/add-user.js
  - name: init rs
    shell: mongosh --port {{ MONGOS_PORT }} -f /opt/cbimeasz/mongo-cluster/add-user.js
    ignore_errors: true

  - name: 拷贝 add-shard.js
    template:
      src: add-shard.js.j2
      dest: /opt/cbimeasz/mongo-cluster/add-shard.js
  - name: init rs
    shell: mongosh -u cbim -p {{ MONGO_PASSWD }} --port {{ MONGOS_PORT }} -f /opt/cbimeasz/mongo-cluster/add-shard.js
    ignore_errors: true
  when: MASTER_MONGO_NODE|bool
