- name: mkdir
  file:
    path: /opt/cbimeasz/redis-cluster
    state: directory
    mode: '0755'
- name: copy rpms
  copy: 
    src: '{{ base_dir }}/down-ext/ruby'
    dest: /opt/cbimeasz/redis-cluster/bin
- name: copy gem
  copy: 
    src: redis-3.2.1.gem
    dest: /opt/cbimeasz/redis-cluster/bin
- name: install ruby rpm
  shell: yum localinstall /opt/cbimeasz/redis-cluster/bin/ruby/*.rpm -y && gem install -l //opt/cbimeasz/redis-cluster/bin/redis-3.2.1.gem
  args:
    warn: false
- name: copy redis-trib.rb
  copy: 
    src: redis-trib.rb
    dest: /opt/cbimeasz/redis-cluster/bin
- name: copy master script
  template:
    src: create-cluster.sh.j2
    dest: /opt/cbimeasz/redis-cluster/create-cluster.sh
- name:
  expect:
    command: ruby /opt/cbimeasz/redis-cluster/bin/redis-trib.rb create --replicas 1 {{ REDIS_NODES }}
    responses:
      'yes': 'yes'
    echo: yes