- name: copy mysql.stream
  template:
    src: mysql.stream.j2
    dest: /etc/nginx/conf.d/mysql.stream

- name: 开启nginx服务
  shell: systemctl daemon-reload && systemctl restart nginx
  ignore_errors: true
  tags: restart_lb

- name: 以轮询的方式等待nginx服务启动
  shell: "systemctl status nginx.service|grep Active"
  register: svc_status
  until: '"running" in svc_status.stdout'
  retries: 3
  delay: 3
  tags: restart_lb