- name: open firewalld port
  shell: firewall-cmd --zone=public --add-port=3306/tcp --permanent && \
         firewall-cmd --zone=public --add-port=33060/tcp --permanent && \
         firewall-cmd --zone=public --add-port=33061/tcp --permanent && \
         firewall-cmd --zone=public --add-port=33062/tcp --permanent && \
         firewall-cmd --reload

- name: change name
  raw: "echo {{hostname|quote}} > /etc/hostname"
- name:
  shell: hostname {{hostname|quote}}
- name: mkdir
  file:
    path: /opt/cbimeasz/mysql-cluster
    state: directory
    mode: '0755'
- name: copy rpms
  copy:
    src: '{{ base_dir }}/down-ext/mysql-cluster'
    dest: /opt/cbimeasz/mysql-cluster/bin
- name: install mysql rpm
  shell: yum erase mariadb-libs -y && yum localinstall /opt/cbimeasz/mysql-cluster/bin/mysql-cluster/*.rpm -y
  args:
    warn: false
- name: copy config
  template:
    src: init-config.sh.j2
    dest: /opt/cbimeasz/mysql-cluster/init-config.sh
- name: exec config script
  shell: sh /opt/cbimeasz/mysql-cluster/init-config.sh
  args:
    warn: false
- block:
    - name: append my.cnf
      shell: echo 'innodb_buffer_pool_size=3G\nmax_connections=1000\nmax_allowed_packet=512M' >> /etc/my.cnf
    - name: restart mysql
      service: name=mysqld state=started

- block:
    - name: stop mysql
      service: name=mysqld state=stopped
    - name: mkdir
      file:
        path: '{{ MYSQL_DATA_DIR }}'
        state: directory
        mode: '0755'
        owner: mysql
        group: mysql
    - name: move mysql
      shell: mv /var/lib/mysql {{ MYSQL_DATA_DIR }}/mysql && \
            sed -i "s/\/var\/lib/{{ MYSQL_DATA_DIR_ESCAPE }}/g" /etc/my.cnf && \
            mkdir -p /var/lib/mysql && \
            chown mysql:mysql /var/lib/mysql && \
            ln -s {{ MYSQL_DATA_DIR }}/mysql/mysql.sock /var/lib/mysql/mysql.sock
    - name: start mysql
      service: name=mysqld state=started
  ignore_errors: true
  when: "MYSQL_DATA_DIR != ''"

- block:
  - name: copy config
    template:
      src: init_cluster.js.j2
      dest:  /opt/cbimeasz/mysql-cluster/init_cluster.js
  - name: exec config script
    shell: mysqlsh --no-password --js --file=/opt/cbimeasz/mysql-cluster/init_cluster.js
  when: MASTER_DB|bool

- name: set MASTER_HOSTNAME of the mysql cluster
  set_fact: MASTER_HOSTNAME="{% for host in groups['mysql_cluster'] %}{% if hostvars[host]['MASTER_DB']|bool %}{{ hostvars[host]['hostname'] }}{% endif %}{% endfor %}"

- name: open firewalld port for mysql router
  shell: firewall-cmd --zone=public --add-port=6446/tcp --permanent && \
         firewall-cmd --zone=public --add-port=6447/tcp --permanent && \
         firewall-cmd --zone=public --add-port=6448/tcp --permanent && \
         firewall-cmd --zone=public --add-port=6449/tcp --permanent && \
         firewall-cmd --reload

- name: start mysql router
  shell: mysqlrouter --bootstrap root:{{ MYSQL_PASSWORD }}@{{ MASTER_HOSTNAME }}:3306 --user=mysqlrouter --force
- name: init systemd
  service: name=mysqlrouter state=started enabled=yes

