- name: mkdir
  file:
    path: /opt/cbimeasz/mongo-cluster
    state: directory
    mode: '0755'
- name: copy rpms
  copy: 
    src: '{{ base_dir }}/down-ext/mongo'
    dest: /opt/cbimeasz/mongo-cluster/bin
- name: install mongo rpm
  shell: yum localinstall /opt/cbimeasz/mongo-cluster/bin/mongo/*.rpm -y
  args:
    warn: false
- name: 关闭默认启动
  service: name=mongod state=stopped enabled=no 

- name: 复制 keyfile
  copy:
    src: '{{ cluster_dir }}/mongo/keyfile'
    dest: '/etc/mongo.keyfile'  
    owner: mongod
    group: mongod
    mode: '0400'