- name: mkdir
  file:
    path: /opt/cbimeasz/redis-cluster
    state: directory
    mode: '0755'
- name: copy rpms
  copy: 
    src: '{{ base_dir }}/down-ext/redis-6.x'
    dest: /opt/cbimeasz/redis-cluster/bin
- name: install redis rpm
  shell: yum localinstall /opt/cbimeasz/redis-cluster/bin/redis-6.x/*.rpm -y
  args:
    warn: false

# 启动 redis server    
- name: mkdir port
  file:
    path: '{{ REDIS_DATA_DIR }}/'
    state: directory
    mode: '0755'
    group: redis
    owner: redis
- name: copy configfile1 to nodes
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
- name: start redis
  service: name=redis state=started enabled=yes
  ignore_errors: yes

- name: 启动集群
  shell: /usr/bin/redis-cli --cluster create --cluster-replicas 1 {{ REDIS_NODES }} --cluster-yes
  ignore_errors: yes
  when: MASTER_NODE|bool