- name: 打开防火墙
  shell: firewall-cmd --zone=public --add-port={{ MONGO_CONFIG_PORT }}/tcp --permanent && \
         firewall-cmd --reload
  ignore_errors: yes
- name: mkdir
  file:
    path: "{{ MONGO_CONFIG_DATA_DIR }}"
    state: directory
    mode: '0755'
    group: mongod
    owner: mongod
- name: 拷贝配置文件
  template:
    src: mongod.conf.j2
    dest: /etc/mongod-config.conf

- name: copy systemd conf
  template:
    src: mongod-config.service
    dest: /usr/lib/systemd/system/mongod-config.service
- name: chmod
  file:
    path: /usr/lib/systemd/system/mongod-config.service
    mode: 0755
- name: start mongod-config
  shell: systemctl daemon-reload
  ignore_errors: yes
- name: 设置开机启动
  service: name=mongod-config state=started enabled=yes
- block:
  - name: 拷贝 rs init.js
    template:
      src: init-rs.js.j2
      dest: /opt/cbimeasz/mongo-cluster/init-config-rs.js
  - name: init rs
    shell: mongosh --port {{ MONGO_CONFIG_PORT }} -f /opt/cbimeasz/mongo-cluster/init-config-rs.js
    ignore_errors: true
  run_once: true
