- name: mkdir
  file:
    path:  /opt/cbimeasz/mysql-cluster
    state: directory
    mode: '0755'
- name: copy config
  template: 
    src: init_cluster.js.j2 
    dest:  /opt/cbimeasz/mysql-cluster/init_cluster.js
- name: exec config script
  shell: mysqlsh --no-password --js --file=/opt/cbimeasz/mysql-cluster/init_cluster.js 