- hosts: nginx_node
  roles:
  - base
  - nginx-node
  - { role: mysql-cluster-lb, when: "groups['mysql_cluster'] is defined and (groups['l4lb_node'] is not defined or groups['l4lb_node']|length == 0) and groups['mysql_cluster']|length > 0" }
  - { role: redis-cluster-lb, when: "groups['redis_cluster'] is defined and (groups['l4lb_node'] is not defined or groups['l4lb_node']|length == 0) and groups['redis_cluster']|length > 0" }
  - { role: nacos-cluster-lb, when: "groups['nacos_cluster'] is defined and (groups['l4lb_node'] is not defined or groups['l4lb_node']|length == 0) and groups['nacos_cluster']|length > 0" }
  - { role: mongos-cluster-lb, when: "groups['mongo_cluster_master'] is defined and (groups['l4lb_node'] is not defined or groups['l4lb_node']|length == 0) and groups['mongo_cluster_master']|length > 0" }
  - { role: rabbitmq-cluster-lb, when: "groups['rabbitmq_cluster'] is defined and (groups['l4lb_node'] is not defined or groups['l4lb_node']|length == 0) and groups['rabbitmq_cluster']|length > 0" }
  - { role: minio-cluster-lb, when: "groups['minio_cluster'] is defined and (groups['l4lb_node'] is not defined or groups['l4lb_node']|length == 0) and groups['minio_cluster']|length > 0" }

- hosts: l4lb_node
  roles:
  - base
  - nginx-node
  - { role: mysql-cluster-lb, when: "groups['mysql_cluster'] is defined and groups['mysql_cluster']|length > 0" }
  - { role: redis-cluster-lb, when: "groups['redis_cluster'] is defined and groups['redis_cluster']|length > 0" }
  - { role: nacos-cluster-lb, when: "groups['nacos_cluster'] is defined and groups['nacos_cluster']|length > 0" }
  - { role: mongos-cluster-lb, when: "groups['mongo_cluster_master'] is defined and groups['mongo_cluster_master']|length > 0" }
  - { role: rabbitmq-cluster-lb, when: "groups['rabbitmq_cluster'] is defined and groups['rabbitmq_cluster']|length > 0" }
  - { role: minio-cluster-lb, when: "groups['minio_cluster'] is defined and groups['minio_cluster']|length > 0" }
