# 自动设置LB节点变量'LB_IF'
- name: 注册变量 LB_IF_TMP
  shell: "ip a|grep '{{ inventory_hostname }}/'|awk '{print $NF}'"
  register: LB_IF_TMP
  tags: restart_lb

- name: 设置变量 LB_IF
  set_fact: LB_IF={{ LB_IF_TMP.stdout }}
  tags: restart_lb

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  # - "/etc/nginx/sbin"
  # - "/etc/nginx/logs"
  # - "/etc/nginx/conf"
  - "/etc/keepalived"

# - name: 下载二进制文件nginx(nginx)
#   copy: src={{ base_dir }}/bin/nginx dest=/etc/nginx/sbin/nginx mode=0755

# - name: 创建nginx的配置文件
#   template: src=nginx.conf.j2 dest=/etc/nginx/conf/nginx.conf
#   tags: restart_lb

# - name: 创建nginx的systemd unit文件
#   template: src=nginx.service.j2 dest=/etc/systemd/system/nginx.service
#   tags: restart_lb

- name: mkdir
  file:
    path: /opt/cbimeasz/nginx
    state: directory
    mode: '0755'
- name: copy rpms
  copy: 
    src: '{{ base_dir }}/down-ext/nginx'
    dest: /opt/cbimeasz/nginx/bin
- name: install nginx rpm
  shell: yum localinstall -y /opt/cbimeasz/nginx/bin/nginx/*.rpm

- name: copy nginx.conf 配置
  copy: 
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: copy apiserver.stream
  template:
    src: apiserver.stream.j2
    dest: /etc/nginx/conf.d/apiserver.stream

- name: 开机启用nginx服务
  shell: systemctl enable nginx
  ignore_errors: true

- name: 开启nginx服务
  shell: systemctl daemon-reload && systemctl restart nginx
  ignore_errors: true
  tags: restart_lb

- name: 以轮询的方式等待nginx服务启动
  shell: "systemctl status nginx.service|grep Active"
  register: svc_status
  until: '"running" in svc_status.stdout'
  retries: 3
  delay: 3
  tags: restart_lb


- name: 下载二进制文件keepalived
  copy: src={{ base_dir }}/bin/keepalived dest=/usr/local/sbin/keepalived mode=0755

- name: 配置 keepalived 主节点
  template: src=keepalived-master.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "master"
  tags: restart_lb

- name: 配置 keepalived 备节点
  template: src=keepalived-backup.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "backup"
  tags: restart_lb

- name: 创建keepalived的systemd unit文件
  template: src=keepalived.service.j2 dest=/etc/systemd/system/keepalived.service
  tags: restart_lb

- name: 开机启用keepalived服务
  shell: systemctl enable keepalived
  ignore_errors: true

- name: 开启keepalived服务
  shell: systemctl daemon-reload && systemctl restart keepalived
  ignore_errors: true
  tags: restart_lb

- name: 以轮询的方式等待keepalived服务启动
  shell: "systemctl status keepalived.service|grep Active"
  register: svc_status
  until: '"running" in svc_status.stdout'
  retries: 3
  delay: 3
  tags: restart_lb
